# Workshop 1 (2017-10-16)

## Table of contents
1. [Esercizi per il tutorial Numpy](#p1)
    1. [Array Creation](#sp1)
    2. [Basic Operation](#sp2)
    3. [Shape Manipulation](#sp3)
    4. [Copies and Views](#sp4)
2. [Esercizi slide](#p2)
    1. [Assignment 1](#sp5)
    2. [Assignment 2](#sp6)
3. [Esempi di utilizzo di Larlib](#p3)
    1. [Esempio 1](#sp7)
    2. [Esempio 2](#sp8)
    3. [Esempio 3](#sp9)
    4. [Esempio 4](#sp10)
    5. [Esempio 5](#sp11)

## Tutorial Numpy <a name="p1"></a>



### Array Creation <a name="sp1"></a>
arange(start, end, stepSize) -> restituisce un array con elementi che vanno da "start" a "end", ognuno incrementato di "stepSize" rispetto al precedente

Va bene sia per int che float.

In [1]:
from IPython.display import display
import numpy as np 

display(np.arange(0, 20, 5))
display(np.arange(0., 5., 0.4))

array([ 0,  5, 10, 15])

array([ 0. ,  0.4,  0.8,  1.2,  1.6,  2. ,  2.4,  2.8,  3.2,  3.6,  4. ,
        4.4,  4.8])

linspace(start, end, nResult) -> simile ad arange, ma il terzo parametro indica il numero di elementi nell'array in output; quindi stepSize è $(end-start)/nResult$

In [2]:
display(np.linspace(0, 2, 9))

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

### Basic Operations <a name="sp2"></a>
La maggior parte delle operazioni agiscono sugli elementi degli array/matrici, inclusa la moltiplicazione. Per calcolare il prodotto cartesiano bisogna quindi usare l'operatore dot o creare degli oggetti np.matrix (su cui effettuare una normale moltiplicazione).

In [3]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])
display(A * B)        #normal product
display(np.dot(A,B))  #cartesian product with dot operator
display(np.matrix(A)*np.matrix(B)) #cartesian product with np.matrix

array([[2, 0],
       [0, 4]])

array([[5, 4],
       [3, 4]])

matrix([[5, 4],
        [3, 4]])

Operatori come $+=$ e $*=$ modificano la matrice in input invece di crearne una nuova in output.

In [4]:
matrix = np.matrix(A)
matrix += 2
matrix

matrix([[3, 3],
        [2, 3]])

La classe ndarray include anche operazioni applicabili a tutti gli elementi dell'array. Nel caso di matrici, si può indicare la dimendione sulla quale si vuole agire.

In [5]:
a = np.random.random((2,3))
display(a)
display(a.max())        #max of all elements
display(a.max(axis=0))  #max of all columns
display(a.max(axis=1))  #max of all rows

array([[ 0.56384035,  0.32929477,  0.89876146],
       [ 0.18773655,  0.58310892,  0.65435841]])

0.89876145584273459

array([ 0.56384035,  0.58310892,  0.89876146])

array([ 0.89876146,  0.65435841])

Si possono iterare gli array come delle liste. Nel caso di matrici si possono usare due indici separati da virgola.

In [6]:
a = np.arange(10)**3
b = np.arange(20).reshape(4,5)
display(a)
a[:6:2] = -1000
display(a)
display(b)
display(b[:5, 1])  #the second element of each row

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

array([ 1,  6, 11, 16])

Indipendentemente dal numero di dimensioni di una matrice, il metodo $flat$ permette di iterare sui singoli elementi.

In [7]:
for elem in b.flat:
    print elem

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


### Shape Manipulation <a name="sp3"></a>
Esistono vari modi per cambiare le dimensioni di un array.

In [8]:
a = np.floor(10*np.random.random((3,4)))
display(a)
display(a.ravel())   #creates a one-dimensional array from a matrix
a.shape = (6,2)
display(a.transpose())

array([[ 4.,  9.,  0.,  7.],
       [ 7.,  7.,  2.,  7.],
       [ 9.,  4.,  0.,  8.]])

array([ 4.,  9.,  0.,  7.,  7.,  7.,  2.,  7.,  9.,  4.,  0.,  8.])

array([[ 4.,  0.,  7.,  2.,  9.,  0.],
       [ 9.,  7.,  7.,  7.,  4.,  8.]])

### Copies and Views <a name="sp4"></a>
Si possono copiare array (ovvero creare nuovi oggetti array a partire da uno già esistente) in due modalità:
   1. View : oggetti differenti che fanno riferimento agli stessi elementi
   2. Deep Copy : copie complete

In [9]:
a = np.arange(12)
a.shape = 3,4
display(a)
c = a.view()
display(c is a)
c.shape = 2,6                      # a's shape doesn't change
display(a.shape)
c[0,4] = 1234                      # a's data changes
display(a)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

False

(3, 4)

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [10]:
s = a[ : , 1:3]     # spaces added for clarity; could also be written "s = a[:,1:3]"
s[:] = 10           # s[:] is a view of s. Note the difference between s=10 and s[:]=10
display(a)

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

## Esercizi Slide <a name="p2"></a>

### Assignment 1 <a name="sp5"></a>
Produce (and draw) 100 random points within the unit square [0,1]$^2$:

In [1]:
from larlib import *
point_list = [(x,y) for (x,y) in np.random.random((100, 2))]
VIEW(STRUCT([MK(point) for point in point_list]))

Evaluating fenvs.py..
...fenvs.py imported in 0.005679 seconds


<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x7f0f90077c30> >

![points](imgs/assignment1.png)

### Assignment 2 <a name="sp6"></a>
Produce (and draw) 1000 random points within $S_1$, the $1D$ sphere (circle) of unit radius centered at the origin (0, 0):

In [12]:
def get_point_circle():
    x = np.random.uniform(-1, 1)
    # y^2+x^2=r^2 => y = sqrt(r^2-x^2)
    limit = sqrt(1-x**2)
    y = np.random.uniform(-limit, limit)
    return (x,y)

point_list = [get_point_circle() for i in range(1000)]
VIEW(STRUCT([MK(point) for point in point_list]))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x7f289aa51ed0> >

![circle](imgs/assignment2.png)

## Esempi di utilizzo di Larlib <a name="p3"></a>

### Esempio 1 <a name="sp7"></a>

La funzione $larSimplexFacets$ estrae (d-1)-facets non orientati da d-simplessi. Ritorna una lista di d-tuple di interi.

In [14]:
def larSimplexFacets(simplices):
    out = []
    d = len(simplices[0])
    for simplex in simplices:
        out += AA(sorted)(
            [simplex[0:k]+simplex[k+1:d] for k in range(d)])
    out = set(AA(tuple)(out))
    return  sorted(out)

In [15]:
simplices = [[1,2,4],[2,4,5],[2,3,5]]
larSimplexFacets(simplices)

[(1, 2), (1, 4), (2, 3), (2, 4), (2, 5), (3, 5), (4, 5)]

### Esempio 2 <a name="sp8"></a>

In [19]:
V = [[0,0], [0,1],[2,0],[4,0],[1.5,3],[3.5,2.5]]
FV = simplices
model = V,FV
VIEW(STRUCT(MKPOLS(model)))
VIEW(SKEL_1(STRUCT(MKPOLS(model))))
EV = larSimplexFacets(FV)
VIEW(STRUCT(MKPOLS((V,EV))))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x7f289aa511b0> >

![esempio2a](imgs/esempio2.png) ![esempio2b](imgs/esempio2b.png)

### Esempio 3 <a name="sp9"></a>
La funzione $larExtrude1$ è una funzione che genera i vertici di un modello in un'estrusione multipla di un modello LAR.

In [20]:
def larExtrude1(model,pattern):
    """ Simplicial model extrusion in accord with a 1D pattern """
    V, FV = model
    d, m = len(FV[0]), len(pattern)
    coords = list(cumsum([0]+(AA(ABS)(pattern))))
    offset, outcells, rangelimit = len(V), [], d*m
    for cell in FV:
            tube = [v + k*offset for k in range(m+1) for v in cell]
            cellTube = [tube[k:k+d+1] for k in range(rangelimit)]
            outcells += [reshape(cellTube, newshape=(m,d,d+1)).tolist()]
    outcells = AA(CAT)(TRANS(outcells))
    cellGroups = [group for k,group in enumerate(outcells) if pattern[k]>0]
    outVertices = [v+[z] for z in coords for v in V]
    outModel = outVertices, CAT(cellGroups)
    return outModel

In [2]:
V = [[0,0],[1,0],[2,0],[0,1],[1,1],[2,1],[0,2],[1,2],[2,2]]
FV = [[0,1,3],[1,2,4],[2,4,5],[3,4,6],[4,6,7],[5,7,8]]
model = larExtrude1((V,FV),4*[1,2,-3])
VIEW(EXPLODE(1,1,1.2)(MKPOLS(model)))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x7f0f8f6e1ba0> >

![esempio3](imgs/esempio3.png)

### Esempio 4 <a name="sp10"></a>

In [3]:
model = larExtrude1( VOID, 10*[1] )
VIEW(EXPLODE(1.5,1.5,1.5)(MKPOLS(model)))
model = larExtrude1( model, 10*[1] )
VIEW(EXPLODE(1.5,1.5,1.5)(MKPOLS(model)))
model = larExtrude1( model, 10*[1] )
VIEW(EXPLODE(1.5,1.5,1.5)(MKPOLS(model)))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x7f0f8e4316c0> >

![esempio4a](imgs/esempio4.png) ![esempio4b](imgs/esempio4b.png) ![esempio4c](imgs/esempio4c.png)

### Esempio 5 <a name="sp11"></a>

In [4]:
model = larExtrude1( VOID, 10*[1,-1] )
VIEW(EXPLODE(1.5,1.5,1.5)(MKPOLS(model)))
model = larExtrude1( model, 10*[1] )
VIEW(EXPLODE(1.5,1.5,1.5)(MKPOLS(model)))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x7f0f8e431db0> >

![esempio5a](imgs/esempio5.png) ![esempio5b](imgs/esempio5b.png)